name: Output Opened Issue
on:
  issues:
    types:
      - opened
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output Issue Context
        run: echo "Issue data: ${{ toJson(github.event.issue) }}"
